### ISSUE TITLE
Setup source mapping for babel

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#126]
I think it would be beneficial for debugging if we setup source mapping for babel.

Thoughts?

**Comment by mitchhentges** [comment]
Jetbrains IDEs require sourcemaps for debugging, so it would help me

**Comment by jonotron** [comment]
This is fixed in #170 

Note: see https://github.com/tickbin/tickbin/pull/170#issuecomment-208444224

TL;DR we need to use the `--source-maps` babel cli option as the `.babelrc` equivalent does not work as expected
