### ISSUE TITLE
Time change caused various edge cases in tests

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#127]
I ran the tests around 11:30 last night (March 12) and had several errors come up which seemed to be related to the time change. The tests with issues all seemed to be the overlapping day ranges like `11pm-2am`.

I was able to use the package [MockDate](https://github.com/boblauer/MockDate) in order to rerun the tests as if it was 11:30pm on March 12 and was able to replicate the results.

<img width="958" alt="screen shot 2016-03-13 at 1 04 01 pm" src="https://cloud.githubusercontent.com/assets/3250463/13730988/5c441cce-e91c-11e5-9174-215fa72d3d74.png">

I was looking into this issue for a bit last night and then it passed midnight and the above error no longer happened, but we then had different failing tests.

Mocking the date to be 12:30am March 13:

<img width="817" alt="screen shot 2016-03-13 at 1 08 16 pm" src="https://cloud.githubusercontent.com/assets/3250463/13731027/22da637a-e91d-11e5-9725-8d2361c6ded4.png">

Relates to #125

**Comment by chrisfosterelli** [comment]
Is this resolved now since we [pin the timezone in tests](https://github.com/tickbin/tickbin/blob/9d3e3182078cdba955b701952978e52d6d586c52/package.json#L13)?
Or does that just hide the problem?

**Comment by jonotron** [comment]
I don't think this is resolved since UTC doesn't observe daylight savings. I might be safer to test for these edge cases specifically by mocking the date

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
