### ISSUE TITLE
Support below Node 4?

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/tickbin#142]
Do we want to eventually add support for Node versions below 4.x, or are we considering that a requirement?

It's probably worth looking into how difficult it is to add.

**Comment by jonotron** [comment]
If it's easy, we could support 0.12, but I don't feel like it's necessary (nor desirable). Doing so would require a separate build process as we currently don't run the full `es2015` set of babel plugins (just the few plugins for features that node v4 does not yet support)

**Comment by chrisfosterelli** [comment]
@jonotron Is there a reason we don't just run `es2015` as a whole, if it easily added 0.12 support?

**Comment by jonotron** [comment]
@chrisfosterelli we removed it in #124 because we thought it might be easier to test as a result (not really planning or thinking about supporting node 0.12). It **is** faster to with the the specific set of plugins.

**Comment by jonotron** [comment]
Decided that we won't support anything below node 4 at this point. We can re-open if someone has a genuine need and discuss then.
