### ISSUE TITLE
Direct users to tickbin.com when registering

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#143]
Currently when a user registers, we ask for all their information and then prompt for a beta key at the end. It might be useful to display a message right at the beginning stating that it is in beta and that they can go to tickbin.com to sign up for the waiting list.

It also might be nice to ask for the beta key first, before making them enter all their information.

**Comment by jonotron** [comment]
Agreed. Let's preface the registration inputs with "Registration currently requires a beta key while we are in testing. Sign up for the waiting list at https://tickbin.com"
