### ISSUE TITLE
Tickbin doesn't imply proper meridiem 

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/tickbin#145]
5:45-6:00 parses as 5:45AM-6:00AM when 5:45PM-6:00PM is desired

I entered this at 6:00PM, so I assumed it would imply the correct meridiem.

![image](https://cloud.githubusercontent.com/assets/2072672/13865557/c984ceb4-ec69-11e5-9ebe-3706fb0d3cc3.png)

#### Potential problem with fixing this
How could our code determine the difference between someone who types 5:45-6:00 in _military time context_ and 5:45-6:00 in _12 hour context_? Assume the time is 6:00PM, so someone in military time context likely means the AM and someone in 12 hour context likely means PM. 

Should we assume that they are only specifying military time if they provide four digits (ex: 05:45-06:00)? If that's the case I think `militaryParser` will need to be fixed.

**Comment by chadfawcett** [comment]
When I personally enter time in 24 hour, I omit the leading zeros. However, since I added some more refiners I have been making an effort to use 24 hours less.

**Comment by chrisfosterelli** [comment]
I agree that it's handy. My thought is that it's not actually standard, 24
hour times should be two digit hours:
https://en.m.wikipedia.org/wiki/24-hour_clock

**Comment by jonotron** [comment]
I agree with standardizing. 24 hour times should parse with leading 0. And we should distinguish between 24 hour time (leading 0) and military time (24 hour time with no delimiter).

**Comment by chrisfosterelli** [comment]
That sounds reasonable :+1: 

Note: Looking now, it seems [`militaryParser`] _only_ deals with `HHMM` or `HMM`, Chrono by itself can identify HH:MM  (but appears to have the issue with the meridiem).

[`militaryParser`]: https://github.com/tickbin/tickbin/blob/master/src/parsers/militaryParser.js#L11

**Comment by jonotron** [comment]
After discussing this we have decided that we must require at least 1 meridiem to be able to parse any time entry. So `5-6` is not sufficient, `5-6pm` would be sufficient.

We may need to revisit this in the future as some sort of guided feature where the interface asks if you meant AM or PM, but for now we won't be fixing this
