### ISSUE TITLE
Get a total for a `tick list` query

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/tickbin#147]
It'd be really nice to get the total time for a given query. Perhaps this could be printed at the bottom of the `tick list` printout or calculated by using a `-s` (for summary) flag. 

Thoughts on what this would look like?

**Comment by jonotron** [comment]
Ya, I like this feature a lot... we should consider #148 and #149 and how they should relate to this (e.g. in terms of the flag name)

Additionally, it would be awesome to get a tag total too (possibly as part of this feature, or maybe another feature/flag

**Comment by chadfawcett** [comment]
I think it could be useful to have the summary along with the details rather than a separate output using a `-s` flag.

I also like @jonotron idea of showing the tag total. Either simply listing the tags that are present in the list, or additionally having a count beside each tag.

**Comment by jonotron** [comment]
I think the feature @chrisfosterelli was going for was an optional output as part of `tick list`... so `-s` would turn on a summary line with total time for the entries included in `tick list` not as a separate output. This is what I would want anyways.

**Comment by chadfawcett** [comment]
Ah okay. Yeah I wasn't sure what was implied.

**Comment by chrisfosterelli** [comment]
This is what I was originally thinking:

```
➜  tick list
Mon, Mar 21, 2016  3h  0m
NJlDNKYTg 02:45am-05:45am  3h  0m Confirm users via email (66) #tickbin
Sun, Mar 20, 2016  0h 15m
Vkz4U4u6x 05:45pm-06:00pm  0h 15m Support for budget questions from Brent #sms
Overall Total      3h 15m
```

```
➜  tick list -s
Overall Total      3h 15m
```

But TBH I am not partial to one way or the other. As long as there is some way to get a total time. I added the question tag since I'm open to ideas on the best approach :)

It may make sense to not display the total all the time and behave more like Jonathan suggested, since I'd need it rarely.

**Comment by chadfawcett** [comment]
I'm cool with @jonotron's approach.

**Comment by jonotron** [comment]
Because we have #148 (hide details) and #149 (hide summary) you could get a simple total line with `tick log --hide-summary --hide-details --summary`

Although as I look at that, `--hide-summary` and `--summary` are too similar.

perhaps `--sum` (and `--sum-tags` to show a tag summary - which should be a separate issue)

**Comment by chrisfosterelli** [comment]
@jonotron Yeah I think that `--sum` makes sense as long as the `--help` for `--hide-summary` is clear it refers to the Daily Summary
