### ISSUE TITLE
9-5 parsed as 20h

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#153]
Do we want this to be assumed as 9am-5pm? Or is this our intended behaviour?

**Comment by jonotron** [comment]
I get the same problem parsing 11-1. I think this should parse depending on the reference date time. If I enter 11-1 at 1:30am I should expect that 11-1 would parse as 11pm-1am.

**Comment by chrisfosterelli** [comment]
Is this related to (or a duplicate) of #145?

**Comment by chadfawcett** [comment]
@chrisfosterelli it's a bit different. Our example has two different meridiems, while #145 has the same meridiems but are the wrong one.

**Comment by jonotron** [comment]
This is related to #145 as chrono, by default, in the absence of a meridiem implies AM. Since we require at least 1 meridiem now, we will not fix this.
