### ISSUE TITLE
Time not found in log 11-5:30pm

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#160]
Not sure if this will be fixed with the changes that are soon to be released...

![screen shot 2016-03-31 at 6 07 43 pm](https://cloud.githubusercontent.com/assets/3250463/14195289/63c830da-f76c-11e5-87f2-9b27d1cd6d4e.png)

Changing the start to have a meridium (`11am`) allowed the parser to see the time.

**Comment by jonotron** [comment]
I could not reproduce this.
