### ISSUE TITLE
Collect full name on registration

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#171]
The web applications use the users full name. We need to collect this information.

**Comment by jonotron** [comment]
I think this should be an optional step in the cli so as to not add undue burden to the user.

**Comment by chadfawcett** [comment]
Would we then collect it on the web, or optionally display the user's username instead?

**Comment by jonotron** [comment]
@chadfawcett We can still collect full name from the CLI, but it should be an optional step that occurs after the required info has already been entered and an account created.

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
