### ISSUE TITLE
Store the user ID on every record

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/tickbin#177]
We need to store the user's ID on a record if they are logged in. If they are not logged in, we should not worry about recording it (possibly set it to `null`).

**Comment by jonotron** [comment]
@chrisfosterelli Is there a distinction between user ID and username? If so, which should be stored on the entry record?

**Comment by chrisfosterelli** [comment]
@jonotron The user ID is the RethinkDB ID, which we use as a primary key
for everything. The username is only enforced to be unique on the software
level, and we don't use it for anything other than display purposes.

We need the actual user ID to be stored on the record.
