### ISSUE TITLE
filter by complex filter strings

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#179]
rather than `tick log -t projectA dev -d "mar 1-31"` we could filter with `tick log -f "#projectA and #dev mar 1-31"`

**Comment by jonotron** [comment]
@tickbin/core Currently we use the `-f`/`--format` flag for output format (`csv`,`json`,`group`)... we could change the `--format` flag to something else or create a new flag for this filter string.

One thought I had was to use the first non-hypenated string argument... e.g.:

    tick log "#projectA and #dev Mar - April"

Is this weird? If it is, then I propose that we change the `--format` flag to something else (perhaps `--type`) and then use `--filter`/`-f` for the filtering.

**Comment by chadfawcett** [comment]
The first non-hyphenated string would make it similar to `tick commit` where we don't use flag for the message. The difference here is that with `tick commit` it is a *required* flag. If we don't provide it, we simply prompt the user for it. While `tick log` functions without any flags and doesn't require a *default* flag value.

I would suggest `--filter / -f` over the non-hyphenated approach, but I'd be okay with either one.

**Comment by jonotron** [comment]
@chadfawcett I'm not sure that I quite follow your reasoning, but I think you are advocating for consistent use of non-hypenated flags (i.e. if used, they should be required) and thus we should use an option flag (like `--filter`).

If so, I think this makes sense.  So I will change the csv/json export to `--type`/`-t` and will introduce `--filter`/`-f`

**Comment by chadfawcett** [comment]
Sorry for the confusion. Yes I was thinking that in order to be consistant, we should use non-hyphenated flags for required inputs for commands. Since a filter is not required for `tick log` we should introduce `--filter / -f`.

**Comment by chrisfosterelli** [comment]
Another option is `-o` for `--output`. I'm good with `-t` though.

**Comment by jonotron** [comment]
@chrisfosterelli I had thought of `--output`, but other apps often use this to specify a filename for output

**Comment by chrisfosterelli** [comment]
@jonotron Yeah, that makes sense 👍
