### ISSUE TITLE
24 hour time?

### ISSUE THREAD

**Issue by LeeBergstrand** [tickbin/tickbin#184]
Does tick support 24 hour time? I use 24 hour time a lot (like my wrist watches and sometimes my computers).

In addition, optional 24 hr time parsing would allow one to type entries faster and more explicitly.

- ```9:45am-9:45pm did some stuff #thuglife```

Could be written as

- ```9:45-21:45 did some stuff #thuglife```
 
or even

- ```9:00am-9:00pm did some stuff #thuglife```

Could be written as

- ```9-21 did some stuff #thuglife```

**Comment by chadfawcett** [comment]
You bet!
<img width="567" alt="screen shot 2016-05-12 at 9 21 04 pm" src="https://cloud.githubusercontent.com/assets/3250463/15237915/782ed5f6-1887-11e6-9c57-f3aa8c82766a.png">

I often use 24 hours time for entry as it's much quicker.

**Comment by jonotron** [comment]
Yup! You can use 24 hour time in most cases. Your above examples should
work fine. Where things get a little tricky is if there is ambiguity. E.g.
Is 8-10 in the morning or in the evening? An AM or PM is required on at at
least one of the times, but we infer it if the time is > 13.

I believe we have some checks for leading zeros to help with this. So if
you entered 08-10 we can infer that 8am-10am is intended. But then it gets
tricky for 10-12.

It also parses military time 0800-1000, which we can do with certainty

We don't have a final plan on how to deal with the ambiguous case of 10-11
etc, but are open to suggestions.

**Comment by LeeBergstrand** [comment]
If no date is specified, check the system time, if the user is posting in the morning assume 10am - 11am,  if the use is posting in the afternoon assume 10pm -11pm

**Comment by jonotron** [comment]
We've discussed that, but we may still be making an incorrect assumption if
entering time at 11:30pm for work done at 10-11am.

But it's still worth discussing further

For now tho, if we know one of the meridiems (am/pm) it will figure it out.
