### ISSUE TITLE
Report network errors for failed login

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#185]
Attempting to login results with the following

![screen shot 2016-05-13 at 11 26 57 am](https://cloud.githubusercontent.com/assets/3250463/15257929/a5de535c-18fd-11e6-9f6c-6b8a631251e7.png)

**Comment by chrisfosterelli** [comment]
Tried it with the new client?

**Comment by chadfawcett** [comment]
This is the most up to date client yes.

**Comment by chrisfosterelli** [comment]
Ah, I believe this is because the new client expects a username to be provided, but the old API does not provide it.

**Comment by chadfawcett** [comment]
Turns out I accidentally had my `.tickbinrc` pointing to my local API server and it wasn't running. Once I started up the server I got the expected `Error Invalid username or password`.

Would it beneficial to have an error come up when it can't find the server? Likely would help for if a user tries to login when they aren't online.

**Comment by chrisfosterelli** [comment]
Yeah, we should definitely report network errors. Good point!

**Comment by chrisfosterelli** [comment]
It looks like we also miss more general errors, such as:

```
Error [Error: Module version mismatch. Expected 46, got 48. This generally implies that leveldown was built with a different version of node than that which is running now.  You may try fully removing and reinstalling PouchDB or leveldown to resolve.]
```

This simply comes out as "undefined" as well. If `err.data` is not defined, we should probably just print the whole `err`.
