### ISSUE TITLE
tickbin NPM README [build | 404]

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#187]
The build status says **404** when viewing the README on [npmjs.com](https://www.npmjs.com/package/tickbin).

![screen shot 2016-05-13 at 12 35 25 pm](https://cloud.githubusercontent.com/assets/3250463/15259645/5a43fc94-1907-11e6-8831-540d6e8253ef.png)

**Comment by chrisfosterelli** [comment]
After a push, npm takes a few minutes to update the README. I'm guessing
the 404 is from our wrecker project that no longer exists and is used by
the old README?

**Comment by chadfawcett** [comment]
Latest release fixes issue

![screen shot 2016-05-13 at 1 01 43 pm](https://cloud.githubusercontent.com/assets/3250463/15260288/e187c926-190a-11e6-92a9-0d493e69d07a.png)
