### ISSUE TITLE
Help message says to "log" instead of "commit"

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#189]
When you do a log that has no entires, the help message says to "...Create some with 'tick log'". Should say 'tick commit'.

![screen shot 2016-05-13 at 1 19 27 pm](https://cloud.githubusercontent.com/assets/3250463/15260782/9090fd14-190d-11e6-993d-ea768cbfeaf9.png)

**Comment by jonotron** [comment]
We could hotfix this soon
