### ISSUE TITLE
Support for Timers

### ISSUE THREAD

**Issue by LeeBergstrand** [tickbin/tickbin#191]
Have you guys thought about tick logging?

```tick start @sometaskid```

```tick end @sometaskid```

**Comment by chrisfosterelli** [comment]
This is on the roadmap :)

It's currently not a big priority, but we'd like to have it. Is this a
preferred use case over time-specified entries for you?

**Comment by LeeBergstrand** [comment]
v6.1.0

**Comment by LeeBergstrand** [comment]
@chrisfosterelli I would say so.

This was kind of my first intuition of what to do when I started using Tick. Usually when I start a job I don't know how long it is going to take and when I complete a Job and go to log its harder to remember specifically when I started. I guess depends on the granularity of your logging. I kind of like using Tick for analytics with ``#stuff`` tag. To see what I am spending my time on (how to optimize). As a result it would be nice to have some sort of time tracking functionality.

**Comment by chrisfosterelli** [comment]
Yeah this definitely depends on your granularity. We generally don't log to
the second or minute, so this isn't a big use case for us initially.

We've heard this from others as well, so thank you for the feedback!

@jonotron, do we have an estimate/ETA of when we'd like to have this
feature?

**Comment by jonotron** [comment]
We don't have a firm timeline, but it sounds like it will need to be the one of the next features built.

**Comment by chrisfosterelli** [comment]
@LeeBergstrand This is coming soon! Check out our soon-to-be-supported commands:

![image](https://cloud.githubusercontent.com/assets/2072672/16431565/0c1dde38-3d36-11e6-9be0-1bbd6224a945.png)

**Comment by LeeBergstrand** [comment]
@chrisfosterelli I will check it out.

**Comment by chadfawcett** [comment]
@LeeBergstrand we've implemented timer functionality on PR #270. Please feel free to play around with it and let us know of any comments/suggestions you may have.
