### ISSUE TITLE
Show progress bar for sync

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/tickbin#196]
If sync takes a while, it looks like it simply hangs. 

At the minimum we should print a message that informs the user to wait or that it may take a little bit of time, at the best we could add a cool UTF8 loading icon or progress bar.

I forget which tool used it, but there was one that had a neat square loading animation. Could be easy to do something like that!

**Comment by chadfawcett** [comment]
[Ava](https://github.com/avajs/ava) has the cool loading square animation for when it's running tests.

**Comment by jonotron** [comment]
that's this: https://www.npmjs.com/package/cli-spinners

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
