### ISSUE TITLE
tick log will output FIELD WOO! when filtering on #tag

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#205]
This is a bug in https://github.com/nolanlawson/pouchdb-find and will be fixed in an upcoming release

**Comment by chrisfosterelli** [comment]
I believe this is fixed since 0.10.2 has been published and updated to by greenkeeper. @jonotron can you verify?

**Comment by jonotron** [comment]
Correct, I've checked this and it is now fixed
