### ISSUE TITLE
Error: couldn't find a usable index. - After Updating

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#206]
After updating to v0.3.0 I got the following error.

![screen shot 2016-05-30 at 5 23 41 pm](https://cloud.githubusercontent.com/assets/3250463/15660085/97e594fe-268b-11e6-8b13-50f167daba52.png)

Subsequent `tick log`s work as expected.

@jonotron... @chrisfosterelli said you could possibly shed some light on this as it may be some sort of race condition with your indexing you recently implemented.

**Comment by jonotron** [comment]
I think this is caused by the same issue causing #223.

**Comment by chrisfosterelli** [comment]
Yeah, I believe this is a duplicate that would be resolved by fixing #223. Can we close this in place of that one?

**Comment by jonotron** [comment]
On the off chance it’s not a duplicate, let’s leave it open for now.

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
