### ISSUE TITLE
run sync on changes since last sync

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#209]
PR #207 removed the logic that maintained a `_local/last_sync` document to keep track of when the last time a sync was run. If a user changes their `REMOTE` location, this `last_sync` document will not reflect seq numbers for the new `REMOTE`. We would need to smartly keep track of where documents were synced to not just the last seq number.

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
