### ISSUE TITLE
CSV output includes trailing comas on entry lines, not on header line

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#233]
```csv
id,date,seconds,msg,tags,icon
B1PF2TqP,Sun Jul 17,7200,wake surfing on Little Shuswap #fun,#fun,
SkhE3acv,Mon Jul 18,3600,talking with Sofia about Disneyland #tickbin,#tickbin,
```

Should these be present or omitted... regardless it should be consistent in header and body.

**Comment by chrisfosterelli** [comment]
@jonotron I think that is because the `icon` field is empty on every record, not because it's a trailing comma.

**Comment by chrisfosterelli** [comment]
Would be related to #226 in this case.

**Comment by jonotron** [comment]
@sofia-scho did your fix for #226 also resolve this issue?

**Comment by sofia-scho** [comment]
checking...

**Comment by sofia-scho** [comment]
Yes it did!

**Comment by chrisfosterelli** [comment]
Great! I'll go ahead and close this
