### ISSUE TITLE
Registration message shows up when you press delete or enter key

### ISSUE THREAD

**Issue by sofia-scho** [tickbin/tickbin#247]
During registration if you press the delete or enter key at any point during registration, the registration message (that informs the user that they need a beta key),  appears above the field you are typing in.
![screen shot 2016-08-04 at 10 06 07 am](https://cloud.githubusercontent.com/assets/20190559/17411002/18548366-5a2b-11e6-99e5-01405d20805d.png)

**Comment by chadfawcett** [comment]
Merged into master in #302
