### ISSUE TITLE
tick timer with no timer gives two redundant messages

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#277]
I think this might be a small bug?

if I have no timers going and I run `tick timer` I get two lines of error messages:

```
Could not list your timer
You do not have a timer started
```

![jonotron jonathans-macbook-pro 2016-08-29 15-20-07](https://cloud.githubusercontent.com/assets/349600/18069479/37bb97a0-6dfc-11e6-81eb-87976c519484.jpg)

I think the more appropriate message here should be the last one, 'You do not have a timer started', maybe with some helpful text 'Try starting one with tick start'

**Comment by chadfawcett** [comment]
This was done on purpose. Basically the "Could not list your timer" is the main message in the catch statement. The second is a more specific message on what caused the error. See (https://github.com/tickbin/tickbin/blob/049f34bf8f98851176b081817dc57d3e1c09cc6d/src/commands/tick-timer.js#L16) and (https://github.com/tickbin/tickbin/blob/049f34bf8f98851176b081817dc57d3e1c09cc6d/src/timers.js#L65)

I'm open to making it a shorter message though.

**Comment by chrisfosterelli** [comment]
Yeah, I think it would be better UX for the tick-timer command to handle that particular error differently than generic errors, since externally one is indicating the failure of our app and one is indicating a mistake the user made.

**Comment by chadfawcett** [comment]
Every other command related to timers does that. So they will need to be changed as well

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
