### ISSUE TITLE
Use different error messages for empty search results

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/tickbin#278]
When the user has no records in tickbin, we show them this message:

> No entries found in tickbin. Create some with 'tick commit'

This is useful if the user actually has no entries, but this message would be confusing in two cases:
1. The user has no entries in the past two weeks. For example, someone goes away for vacation for three weeks, comes back and runs `tick log`.
2. The search period has no results. For example, `tick log -f 'june 15th, 2012 - june 17th, 2012'`

The current message above is not technically correct, because it's not that there are _no entries at all_, there are just no entries in either the past two weeks (1) or the provided search term (2). 

In the case of search (2), they probably shouldn't be prompted to create entries either because the time period they are searching has possibly well passed.

**Comment by jonotron** [comment]
Maybe we should message differently depending on how the `tick log` was run... e.g. vanilla `tick log` returning no results should probably prompt them to create entries... while `tick log -f "April"` should say "No entries found in tickbin that match your filter"

**Comment by chrisfosterelli** [comment]
@jonotron Yup! I'm thinking there is three cases with different messages:

1. User runs `tick log -f` with a filter and has no results
2. User runs `tick log` and has never created an entry
3. User runs `tick log` and has no entries in the past two weeks

**Comment by jonotron** [comment]
Great! Although, if `tick log -f` and a user has never created an entry, it should probably return the same message as `tick log` and has never created an entry

**Comment by chrisfosterelli** [comment]
Yeah good point... might be a pain to detect all these scenarios though, will have to see what makes the most sense.

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
