### ISSUE TITLE
Shouldn't allow a timer to not have a message

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#279]
Currently if you start and stop a timer with no message other than just time, an entry is created with no message. We need to check if the message given to `tick stop` is time only, then prompt for a commit message.

Entries that have no message fail to sync.

**Comment by jonotron** [comment]
We should also then either allow entries to sync that do not have a message, or add an upgrader that will *fix* these entries to have a message (perhaps "no message provided")?

**Comment by chrisfosterelli** [comment]
I think this boils down to: _is it valid to have a record with no message?_

Currently in the client and server, the answer is no so I would opt toward the upgrader fix. If this is a thing we want to change for UX reasons though then changing the validator may make more sense.

**Comment by jonotron** [comment]
We should require a message, otherwise the entry has no meaning.

**Comment by chadfawcett** [comment]
@jonotron Since I believe I'm the only one that has entries with no message from this problem, and it's in my dev setup, is it worthwhile making an upgrade script for this?

**Comment by jonotron** [comment]
Probably not, your call. Can always be created later.

**Comment by chadfawcett** [comment]
Merged into master in #302
