### ISSUE TITLE
specify .tickbinrc file from command flag

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#285]
We should allow specifying a `.tickbinrc` file via a flag to the command line.

When in development, I use an alias to my development directory (namely `dtick` - for development tick) and a `.tickbinrc` file in my development directory. This works fine when I my PWD is my development directory as `dtick`, which references the `./build/tick.js` file, will use my development `.tickbinrc` file.

However, if I am outside of the development directory and run `dtick`, my development version of `tick` will run, but it will use my `~/.tickbinrc` file and do things to my local (live) tickbin database.

If I could specify my alias with a flag to force the `.tickbinrc` location, that would fix my issue.

I'm open other suggestions tho too

**Comment by chrisfosterelli** [comment]
@jonotron Pass the `--config` argument to your tickbin binary in your alias :)

**Comment by jonotron** [comment]
This works great! Thanks.

**Comment by jonotron** [comment]
@chrisfosterelli do you understand how the `--config` flag worked? It is breaking in #325 but I can't find anything explicitly handling a `--config` flag?

**Comment by jonotron** [comment]
@chrisfosterelli solved this. yargs seems to require explicitly defining options and displays an error if a random flag is supplied.

**Comment by jonotron** [comment]
or rather, we use `.strict()` which was displaying the error
