### ISSUE TITLE
update lodash to 4.x

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#29]
I tried this briefly, but npm **WARN**s that many of the dependencies are looking for lodash `3.x`. I suspect we need to update all the dependencies or somehow suppress the warning

**Comment by chrisfosterelli** [comment]
This seems odd to me because wouldn't it just install lodash 3.x for those particular packages, and use 4.x for ours?

**Comment by jonotron** [comment]
Ya. It's fine now. Also npm 3 seems less panicky
