### ISSUE TITLE
Gracefully handle server down problems when trying to tick sync

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#303]
If the couch server goes down and you try to `tick sync` you will get some error like:

    (node:73531) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'id' of undefined

It should handle this problem more gracefully and inform the user to try again later.

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
