### ISSUE TITLE
Entry index doc is being revised every time a command is run

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/tickbin#312]
We are using the **created** event emitted from PouchDB to create the index doc. The **created** event is not emitted when a new database is created as we initially thought, but rather whenever a new instance of PouchDB is created.

I have confirmed I have over 450 revisions of the `_design/entry_index` doc in my local db

Problem code:
https://github.com/tickbin/tickbin/blob/57b5f0b6865fbc8b0b7409cd65a7f14c149a060b/src/db.js#L12

**Comment by chadfawcett** [comment]
The only other even emitted is the **destroyed** event. So I’m assuming the workaround would be to simply query for the index doc to see if it exists before created it.

**Comment by jonotron** [comment]
Agreed. This may also be able to solve #223, thought solving that should not be a main goal of this.

**Comment by chadfawcett** [comment]
It appears this may actually be an upstream issue https://github.com/nolanlawson/pouchdb-find/issues/161
