### ISSUE TITLE
parsing "2:30-3:30 meet ..." parses as duration instead of erroring

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#319]
I believe this should have errored complaining about a missing merdian, instead it parsed as a duration. Possibly because it extracted the "m" from "meet" as minutes? 

![pocaws-snapshots 2016-11-17 15-32-42](https://cloud.githubusercontent.com/assets/349600/20412427/7693ce3e-acdb-11e6-9597-c7c6bc598d19.jpg)

**Comment by chrisfosterelli** [comment]
I think I have a related issue to this, it seems anywhere in the string if a m/h letter is detected with a number somewhere before it, it parses it as a duration. Here is another erronous example:

![image](https://cloud.githubusercontent.com/assets/2072672/21236180/d6acfcee-c2ae-11e6-98bc-566152f33d42.png)

**Comment by jonotron** [comment]
sounds like it needs a whitespace token in the regexp
