### ISSUE TITLE
rewrite tests in jest

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#327]
We have been really liking jest lately, and it reduces the complexity of tests (and the required modules footprint - we will be able to get rid of sinon, sinon plugins, and tape)

We might be able to use one of the code mods to do the migration for us with some cleanup afterwards https://facebook.github.io/jest/docs/migration-guide.html#content

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
