### ISSUE TITLE
does not sync until I logout then login

### ISSUE THREAD

**Issue by jonotron** [tickbin/tickbin#344]
I just setup a new computer so I did not have any local database. I installed tickbin and then did a `tick login` then `tick sync`. It successfully retrieved my time entries, but any new entry I create will not sync when I later type `tick sync`. I must logout, then login again before entries will sync. Once I have synced, any new entries I create will not sync and I must repeate the logout/login procedure to get entries to sync.

**Comment by jonotron** [comment]
I believe this is because `tick login` is not updating my `.tickbinrc` file with the required `user`

**Comment by chadfawcett** [comment]
The intermediate fix is to add the `user` field to your `.tickbinrc` with your user `id` which can be found in the `remote` url.

Example:
```
user=d5d8ba8d-9731-4ace-a675-2a72673025ca
remote=https://user-d5d8ba8d-9731-4ace-a675-2a72673025ca:<pass>@couch.tickbin.com:443/user-d5d8ba8d-9731-4ace-a675-2a72673025ca
```

**Comment by jonotron** [comment]
:+1: Thanks for the update. I was able to figure this out after looking at my old `.tickbinrc` but forgot to include the workaround.

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
