### ISSUE TITLE
Provide a `tick edit` command

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/tickbin#8]
Often I will log an entry, and then need to change it later.

For example:
1. Chris creates an entry for 1:30-2:30 Testing tickbin
2. Chris needs to extend that entry to 3:00, but can't do it without creating a separate entry with the same name

Perhaps something like `tick extend 3:00` where it just extends your last task? Or maybe we could benefit from some sort of more general edit functionality.

@jonotron thoughts?

**Comment by jonotron** [comment]
I'm changing the scope of this to be an `tick edit` command to allow editing of previously created entries

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
